cc_transactions_lake:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ':memory:'
      threads: 1
      extensions:
        - httpfs
      settings:
        s3_region: "{{ env_var('AWS_DEFAULT_REGION', 'us-east-1') }}"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID', '') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY', '') }}"
        s3_session_token: "{{ env_var('AWS_SESSION_TOKEN', '') }}"
